#ifndef PROTOCOL_H
#define PROTOCOL_H

typedef unsigned int uint;

enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN=0,
    //注册
    ENUM_MSG_TYPE_REGIST_REQUST,
    ENUM_MSG_TYPE_REGIST_RESPONSE,
    //登录
    ENUM_MSG_TYPE_LOGIN_REQUST,
    ENUM_MSG_TYPE_LOGIN_RESPONSE,
    //查找用户
    ENUM_MSG_TYPE_FIND_USER_REQUST,
    ENUM_MSG_TYPE_FIND_USER_RESPONSE,
    //在线用户
    ENUM_MSG_TYPE_ONLINE_USER_REQUST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPONSE,
    //添加好友
    ENUM_MSG_TYPE_ADD_FRIEND_REQUST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPONSE,
    //同意添加好友
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_REQUST,
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_RESPONSE,
    //刷新在线好友
    ENUM_MSG_TYPE_REFRESH_ONLINE_FRIEND_REQUST,
    ENUM_MSG_TYPE_REFRESH_ONLINE_FRIEND_RESPONSE,
    //删除在线好友
    ENUM_MSG_TYPE_DEL_ONLINE_FRIEND_REQUST,
    ENUM_MSG_TYPE_DEL_ONLINE_FRIEND_RESPONSE,
    //聊天
    ENUM_MSG_TYPE_CHAT_REQUST,
    ENUM_MSG_TYPE_CHAT_RESPONSE,
    //创建文件夹
    ENUM_MSG_TYPE_MKDIR_REQUST,
    ENUM_MSG_TYPE_MKDIR_RESPONSE,
    //刷新文件夹
    ENUM_MSG_TYPE_REFRESH_FILE_REQUST,
    ENUM_MSG_TYPE_REFRESH_FILE_RESPONSE,
    //删除文件夹
    ENUM_MSG_TYPE_DEL_DIR_REQUST,
    ENUM_MSG_TYPE_DEL_DIR_RESPONSE,
    //删除文件
    ENUM_MSG_TYPE_DEL_FILE_REQUST,
    ENUM_MSG_TYPE_DEL_FILE_RESPONSE,
    //重命名文件
    ENUM_MSG_TYPE_RENAME_FILE_REQUST,
    ENUM_MSG_TYPE_RENAME_FILE_RESPONSE,
    //移动文件
    ENUM_MSG_TYPE_MOVE_FILE_REQUST,
    ENUM_MSG_TYPE_MOVE_FILE_RESPONSE,
    //上传文件
    ENUM_MSG_TYPE_UPLOAD_FILE_REQUST,
    ENUM_MSG_TYPE_UPLOAD_FILE_RESPONSE,
    //上传文件数据
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPONSE,
    //分享文件
    ENUM_MSG_TYPE_SHARED_FILE_DATA_REQUST,
    ENUM_MSG_TYPE_SHARED_FILE_DATA_RESPONSE,
    //同意分享文件
    ENUM_MSG_TYPE_AGREE_SHARED_FILE_REQUST,
    ENUM_MSG_TYPE_AGREE_SHARED_FILE_RESPONSE,
    ENUM_MSG_TYPE_MAX=0x3f3f3f3f
};

struct PDU{
    uint uiPDULen;
    uint uiMsgLen;
    uint uiMsgType;
    char caData[64];
    char caMsg[];
};
struct FileInfo{
    char caFileName[32];
    uint uiFileType;
};

PDU *mkPDU(uint uiMsgLen);

#endif // PROTOCOL_H
